networks:
  app-tier:
    driver: bridge
services:
  db:
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    hostname: db
    image: mysql:5.7
    networks:
    - app-tier
    platform: linux/x86_64
    ports:
    - 32000:3306
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    build: ./app
    container_name: flask
    depends_on:
      - db
    command: python PrimaryController.py
    environment:
      SQL_DATABASE: intel
      SQL_HOST: db
      SQL_PASSWORD: root
      SQL_PORT: '3306'
      SQL_USER: root
    links:
    - db
    restart: on-failure
    networks:
    - app-tier
    ports:
    - 5050:5050
version: '3'
